[package]
edition = "2021"
license = "MIT"
name = "bevy_gui_bundle_builder"
version = "0.10.1"


[dependencies]
bevy = { version = "0.10", default-features = false, features = [ "bevy_core_pipeline", "bevy_render", "bevy_pbr", "bevy_sprite", "bevy_asset","bevy_text","bevy_ui" ] }

[features]

